### ISSUE TITLE
Reasoning inconsistency for disjoint sets of classes

### ISSUE THREAD

**Issue by visraj1** [phillord/hermit-reasoner#10]
Hi,

I had been trying to use OWL API to check if an ontology is consistent or not. When I try to run the reasoner on Protege I get the correct inconsistency due to the disjointedness  as in the figure below. 
![image](https://user-images.githubusercontent.com/22190957/40715113-d7fda028-6404-11e8-9d6e-de68f66343d8.png)

But when I use the same ontology with the OWL API, its returning true for `hermit.isConsistent()`. Is it due to the wrong usage of the reasoner. I have provided the code below as well . 
Both `Reasoner` and `Configuration` are from the package `org.semanticweb.HermiT`

> Configuration config=new Configuration();
	Reasoner hermit = new Reasoner(config,ontology);	
	if(hermit.isConsistent()) {
		System.out.print("Running safe");
	}

**Comment by ignazio1977** [comment]
Already answered on the owlapi tracker. The right tracker for hermit issues is on the clone of this repository, under my username.
