### ISSUE TITLE
Using Hermit from command line to retrieve individuals beloning to an OWL Class expression

### ISSUE THREAD

**Issue by Demirrr** [phillord/hermit-reasoner#15]
Is it possible to use Hermit **from command line** to infer individuals beloning to an OWL Class Expression on a given RDF knowledge graph ?

**Comment by ykazakov** [comment]
I do not think that HermiT can query for class instances from the command line, but you can easily write a simple Java program that does it, and call it from the command line. See [DL query example](https://github.com/owlcs/owlapi/blob/version5/contract/src/test/java/org/semanticweb/owlapi/examples/DLQueryExample.java).

**Comment by Demirrr** [comment]
Cheers
